___

<a href='http://www.pieriandata.com'> <img src='../../Pierian_Data_Logo.png' /></a>
___

# SF Salaries Exercise 

Welcome to a quick exercise for you to practice your pandas skills! We will be using the [SF Salaries Dataset](https://www.kaggle.com/kaggle/sf-salaries) from Kaggle! Just follow along and complete the tasks outlined in bold below. The tasks will get harder and harder as you go along.

** Import pandas as pd.**

In [1]:
import pandas as pd

** Read Salaries.csv as a dataframe called sal. **

In [2]:
sal = pd.read_csv("Salaries(exercise).csv")

** Check the head of the DataFrame. **

In [3]:
sal.head()

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

**What is the average BasePay ?**

In [4]:
# 66325.44884050643
sal["BasePay"].mean()

66325.4488404877

** What is the highest amount of OvertimePay in the dataset ? **

In [5]:
# 245131.88
sal["OvertimePay"].max()

245131.88

** What is the job title of  JOSEPH DRISCOLL ? Note: Use all caps, otherwise you may get an answer that doesn't match up (there is also a lowercase Joseph Driscoll). **

In [6]:
# 24    CAPTAIN, FIRE SUPPRESSION
# Name: JobTitle, dtype: object
sal["JobTitle"].loc[sal["EmployeeName"] == "JOSEPH DRISCOLL"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

** How much does JOSEPH DRISCOLL make (including benefits)? **

In [7]:
# 24    270324.91
# Name: TotalPayBenefits, dtype: float64
sal["TotalPayBenefits"].loc[sal["EmployeeName"] == "JOSEPH DRISCOLL"]

24    270324.91
Name: TotalPayBenefits, dtype: float64

** What is the name of highest paid person (including benefits)?**

In [8]:
sal.sort_values("TotalPayBenefits").tail(1)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN

** What is the name of lowest paid person (including benefits)? Do you notice something strange about how much he or she is paid?**

In [9]:
sal.sort_values("TotalPayBenefits").head(1)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148653,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,NaN

** What was the average (mean) BasePay of all employees per year? (2011-2014) ? **

In [10]:
sal.groupby(["Year"])["BasePay"].mean()

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

** How many unique job titles are there? **

Read about the "nunique" function

In [11]:
# 2159
sal["JobTitle"].nunique()

2159

** What are the top 5 most common jobs? **

In [12]:
sal.groupby("JobTitle")["JobTitle"].count().sort_values(ascending=False).head()

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

** How many Job Titles were represented by only one person in 2013? (e.g. Job Titles with only one occurence in 2013?) **

In [13]:
# 202
jobs = sal.loc[sal["Year"] == 2013]["JobTitle"]
len(jobs.unique()[jobs.value_counts() == 1])

202

In [14]:
len(sal.loc[sal["Year"] == 2013].groupby(["JobTitle"]).filter(lambda x: len(x) == 1))

202

** How many people have the word Chief 

---

in their job title? (This is pretty tricky) **

In [15]:
sal["JobTitle"].loc[sal["JobTitle"].str.contains("chief",case=False)].count()

627

In [16]:
# ans is 627

 Is there a correlation between length of the Job Title string and Salary? **

In [17]:
sal["JobTitle"].apply(len).corr(sal["TotalPayBenefits"])

-0.03687844593260671

# Great Job!